
######## Parameters you MUST set #########

# location of bam files
samples:
  WT_1: data/samples/DCP2_subsample1Aligned.out.bam
  WT_2: data/samples/DCP2_subsample2Aligned.out.bam

# location of annotation gtf file
annotation: data/annotation/Homo_sapiens.GRCh38.104.chr.gtf

# location of genome fasta file
genome_fasta: data/genome/Homo_sapiens.GRCh38.dna.chr.fa

######## Parameters you should probably double check ########

# Number of cpus to be used by pieline
cpus: 4

# Format of reads
FORMAT: "PE" # (PE, SE, NU)
                    # [SE - single end reads]
                    # [NU - including non-unique] (not tested)

# Number of reads per fragment when splitting up bam file
fragment_size: 25000


# Type of mutations of interest
mut_tracks: "TC" # ("TC", "GA", "TC,GA")

# whether to make .tdf files or not
make_tracks: True

# Minimum base quality to call mutation
minqual: 40

# Which columns to keep in final cB.csv.gz file
keepcols: "sample,sj,io,ei,ai,GF,XF,rname"


######## Parameters you should NEVER alter ########
awkscript: workflow/scripts/fragment_sam.awk
mutcall: workflow/scripts/mut_call.py
mutcnt: workflow/scripts/count_triple.py
count2tracks: workflow/scripts/count_to_tracks.py
